name: Update Extensions

on:
  schedule:
    - cron: "45 * * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2]

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 20

      - run: pnpm install --frozen-lockfile
      - run: pnpm run command update ${{ matrix.shard }}/${{ strategy.job-total }}

      - uses: actions/upload-artifact@v4
        with:
          name: data-${{ matrix.shard }}
          path: data/shard/*.json
          retention-days: 1

  commit:
    name: Commit
    runs-on: ubuntu-latest
    needs: [update]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/download-artifact@v4
        with:
          path: data/shard
          pattern: data-*
          merge-multiple: true

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 20

      - run: pnpm install --frozen-lockfile
      - run: pnpm run command combine

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: update extensions"
